name: nik_validator
description: NIK Validator is a package that functions to parse Identity Card information in Indonesia
version: 1.1.2
author: 
homepage: https://github.com/block7code/nik_validator.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/wilayah.json